### ISSUE TITLE
Navigation bar shows up when pressing anything

### ISSUE THREAD

**Issue by MACEDONIAz** [skyline-emu/skyline#302] opened 2022-01-06 17:10 UTC
### Issue
When touching any OSC button the navigation bar will show up.

### Device
Poco F1
SD845 
6GB Ram
Android 11

### Video 
https://user-images.githubusercontent.com/57722123/148422142-d8b67d59-0b1d-4e02-864c-500fd46a82ab.mp4

**Comment by MACEDONIAz** [comment] 2022-01-06 17:10
by the way the phone i'm using is a poco f1 with a snapdragon 845 and 6gb of ram

**Comment by PixelyIon** [comment] 2022-01-06 19:34
Thanks for the report, we have a tester with issues concerning the navigation bar and will investigate this with them. The issue will be updated when we figure it out and deploy a fix.

**Comment by misakayao** [comment] 2022-01-06 19:34
您的邮件我已收到，感谢您的来信！

**Comment by lynxnb** [comment] 2022-01-12 18:20
Could you try again and see if the issue is fixed in the latest `ftx1` build? You can get it here https://github.com/skyline-emu/skyline/actions/runs/1683103904

**Closed** 2022-03-26 23:13 UTC
