### ISSUE TITLE
Please Make Skyline Emulator can playable in Mediatek and other

### ISSUE THREAD

**Issue by Hirariserla** [skyline-emu/skyline#1854] opened 2022-09-12 14:27 UTC
Please Make Skyline Emulator can playable in Mediatek and other. Because I poor to buy nitendo switch, PC or Gamesir x2.

**Comment by Sovietfowl** [comment] 2022-09-12 14:30
Duplicate of issue #1820.

**Closed by Sovietfowl** 2022-09-12 14:30 UTC

**Comment by guranu** [comment] 2022-09-13 10:10
Get a job.

**Comment by Allatel** [comment] 2022-09-15 11:55
nobody commenting that he has no switch, zulul
