### ISSUE TITLE
Bug graphic

### ISSUE THREAD

**Issue by Miftah35** [skyline-emu/skyline#1111] opened 2022-04-27 09:39 UTC
![Screenshot_2022-04-27-16-38-29-94](https://user-images.githubusercontent.com/102598893/165489797-b7223410-5e88-49e2-93c3-feb48fc7dc5b.jpg)
I playing on mediatek g70 and after update game graphic is bug

**Comment by HalogenGam3r** [comment] 2022-04-27 10:04
You have a lower GPU than Snapdragon. I'll advise you to get a better phone.

**Comment by PixelyIon** [comment] 2022-04-27 11:53
Duplicate of #987.

**Closed by PixelyIon** 2022-04-27 11:53 UTC

**Comment by davyson123** [comment] 2022-04-28 14:56
> ![Captura de tela_2022-04-27-16-38-29-94](https://user-images.githubusercontent.com/102598893/165489797-b7223410-5e88-49e2-93c3-feb48fc7dc5b.jpg) Estou jogando no mediatek g70 e depois de atualizar o gráfico do jogo é bug

Como vc fez isso ?
