### ISSUE TITLE
Segmentation fault while compiling shaders

### ISSUE THREAD

**Issue by Mohamad2008same** [skyline-emu/skyline#416] opened 2022-03-07 16:52 UTC
Plsss fix mali gpu crash

**Comment by Bibiloux98** [comment] 2022-03-07 17:06
That'll be done at some point. Please avoid to open issues until you have an unknown issue to submit

**Comment by ChrisM20** [comment] 2022-03-08 04:52
The last update, I have tried to run sonic mania but it takes me out of the emulation when it worked correctly

**Comment by ndemeyvan** [comment] 2022-03-08 05:41
I also had the same problem, I have a heliog95, I was able to play celeste,
but Sonic mania and hollow knight crash when I try to play it

**Comment by DarxGamer** [comment] 2022-03-08 23:33
I have the same problem, Sonic Mania crash and I was able to launch it a couple of days before
GPU: Mali-G76
CPU: Kirin 990
Huawei P40

**Comment by PixelyIon** [comment] 2022-03-10 14:51
We will look into this sometime next week when one of our developers can access their Mali device.

**Comment by sauradipdebnath** [comment] 2022-03-17 07:59
Are Devs working on that

**Comment by sauradipdebnath** [comment] 2022-03-19 06:13
Don't forget to fix it

**Comment by sauradipdebnath** [comment] 2022-03-19 06:14
Please fix it some time if possible

**Comment by PixelyIon** [comment] 2022-03-19 06:27
We are working on it, we were unable to find the time to do it last week so it'll probably be done this week.

**Comment by Themailkid** [comment] 2022-03-20 02:31
Nice thx guys

**Comment by PixelyIon** [comment] 2022-03-25 18:38
I wanted to add an update, we did figure out what the issue is and I will work on while I'm working on an in-memory shader cache which is what I'll be working on after what I'm working on right now.

**Comment by ibmeto** [comment] 2022-03-27 05:20
> I wanted to add an update, we did figure out what the issue is and I will fix it while I'm working on an in-memory shader cache which is what I'll be working on next.

Thanks, looking forward for the update

**Comment by Long0602** [comment] 2022-03-27 11:09
大力支持这款模拟器，我有switch这款设备，但是我依然支持做模拟器的作者，因为我的朋友就是因为在我电脑上玩过yuzu上的马力欧奥德赛才觉得买的正版

**Comment by PixelyIon** [comment] 2022-03-27 11:17
@Long0602 Hey there, we appreciate the kind words but this is an English-only forum as it's extremely hard to moderate when people are speaking many different languages.

**Comment by sauradipdebnath** [comment] 2022-03-30 15:43
Everyone is asking for Mali GPU Support. So Fix it when you finish working Mario Odyssey and BOTW

**Comment by sauradipdebnath** [comment] 2022-04-01 15:54
Now you can fix it. DON'T Try to drop Mali GPU Support

**Comment by PixelyIon** [comment] 2022-04-03 12:09
This should potentially be fixed by e036935ac137e815efc1d8e15534c11f2af609cc, I'd recommend testing on that and reporting back if this has been fixed.

**Comment by ibmeto** [comment] 2022-04-03 16:28
> This should potentially be fixed by [e036935](https://github.com/skyline-emu/skyline/commit/e036935ac137e815efc1d8e15534c11f2af609cc), I'd recommend testing on that and reporting back if this has been fixed.

I tested the build and it still is the same

**Comment by sauradipdebnath** [comment] 2022-04-03 17:03
Find more commits to fix more crashes or even Mali crash

**Comment by ChrisM20** [comment] 2022-04-08 20:00
Last update without repair yet, it kicks me out of gaming (sonic mania) on a huawei mate 20

**Comment by ibmeto** [comment] 2022-04-09 13:20
Any updates on the mali gpu fixes?

**Closed** 2022-04-12 05:03 UTC

**Comment by Meet97244** [comment] 2023-01-05 07:26
I have crash on Pokemon Sword by going in Motostock city
