### ISSUE TITLE
Broken Audio with AAC headphones

### ISSUE THREAD

**Issue by mjcox244** [skyline-emu/skyline#143] opened 2021-03-12 06:48 UTC
Whenever I use my AAC compatible Bluetooth headphones on skyline the audio is stuttery and lagy

But as soon as I change the codec to SBC it works fine

**Comment by PixelyIon** [comment] 2021-03-12 06:58
This is something that's out of the scope of Skyline itself and should be tackled at the system level, we don't control the host audio output beyond sending it the audio data. 

As a result of this, I'll be closing this issue, file one with your smartphone or headphone OEM.

**Comment by mjcox244** [comment] 2021-03-12 07:00
I just assumed that it may be application level issue as dolphin handles this codec fine

**Comment by PixelyIon** [comment] 2021-03-12 07:06
If I had to guess, it is likely due to the quality of the audio data being lower on Dolphin compared to Skyline (16b 48kHz @ 2ch) which might not be handled by your device adequately. Down-sampling this to lower quality audio should be handled on the host audio stack's end and not Skyline.

**Comment by mjcox244** [comment] 2021-03-12 07:12
Ah that makes more sense now

AAC is marked as "high quality audio" by miui so most likely it's sending the raw data to these headphones that can't handle the bandwidth

That will also explain how SBC fixes it

Thank you for explaining this to me

**Comment by PixelyIon** [comment] 2021-03-20 18:28
I can reproduce this issue myself now, we have a prospective fix by setting a few [Oboe](https://github.com/google/oboe) flags. It'll be PR'd to master soon enough.

**Closed** 2021-03-22 21:10 UTC
