### ISSUE TITLE
Graphic glitch on hollow knight snapdragon 855 adreno 640

### ISSUE THREAD

**Issue by rosenimcute** [skyline-emu/skyline#1611] opened 2022-06-23 05:42 UTC
Graphic glitch on hollow knight snapdragon 855 adreno 640. Black screen with rectangular gray bar and blinking green rectangle. Kindly see attached screenshot.
![Screenshot_20220623-133939_Skyline](https://user-images.githubusercontent.com/104092390/175223662-2d4c77db-84e8-4912-9cab-6eca92377afa.jpg)

**Comment by Sovietfowl** [comment] 2022-06-23 05:59
Duplicate of issue #1587.

**Closed by Sovietfowl** 2022-06-23 05:59 UTC
