### ISSUE TITLE
Stuttering and out of sync sound 

### ISSUE THREAD

**Issue by SombraShadow** [skyline-emu/skyline#1966] opened 2022-11-07 17:35 UTC
Well, I'm writing through a translator, so if there's a mistake, I'm sorry :)
The sound of the games (pokémon Lets Go for example) stutters and loses sync over time, even at 30 fps the sound have bugs,and does not have any sound-related settings or fixes.
Could you tell me if you are going to add at least some configuration related to the sound to fix this? (I'm using Skyline Edge V9).

**Comment by PixelyIon** [comment] 2022-11-07 18:09
Hi, there's no such configuration as this error is caused by inaccuracies in our `audren` implementation. This will be fixed in future updates, till then I'll leave this issue open.

**Comment by ChrisM20** [comment] 2022-11-13 12:21
I also have the same problem but in pokemon sword, it happens when I change places or after a few minutes, I also see that in many gpu in my case Mali g76 it looks blurry in cinematics and some parts, I see that if I remove an object in part of camp can reduce the blur, maybe a hack type option similar to this can fix it.
![Screenshot_20221113_060201_skyline emu](https://user-images.githubusercontent.com/60308449/201521022-f07f0f09-352d-4831-863f-83a5e7506e59.jpg)
![Screenshot_20221113_060248_skyline emu](https://user-images.githubusercontent.com/60308449/201521026-c738bf0a-f6cb-4a0e-9dfd-b42e81820fe6.jpg)
![Screenshot_20221113_060346_skyline emu](https://user-images.githubusercontent.com/60308449/201521040-3e779788-ebdc-4d11-b440-9f56c4db2d46.jpg)

**Comment by SombraShadow** [comment] 2022-11-13 13:59
Ah, I forgot to mention that my phone is a G9 Plus (Snapdragon 730G and 4GB Ram).
And I updated to Edge V11 and the sound bug still persists.

**Closed** 2023-04-25 09:22 UTC
Labels: audren
