### ISSUE TITLE
GPU Mali-G52 MP2 

### ISSUE THREAD

**Issue by KimaLeon** [skyline-emu/skyline#1866] opened 2022-09-17 06:18 UTC
Hello, why can't I run any games on the Skyline emulator, Infinix HOT 12 phone, Android 12, 6 GB RAM, Mediatek Helio G85 processor. I can't even start the Classic Sonic Mania, 3 seconds after launch and freezes, which is sometimes a shame
![Screenshot_20220917-131537](https://user-images.githubusercontent.com/91417289/190843414-0939994a-0117-4802-b6ec-30e8e495a964.jpg)
![Screenshot_20220917-131523](https://user-images.githubusercontent.com/91417289/190843417-14d33f74-31c0-406a-9b62-647401e3f495.jpg)
Sonic Mania APK file It's going fine, but there is no way at all on the emulator.

**Comment by Sovietfowl** [comment] 2022-09-17 07:56
Duplicate of issue #1820.

**Closed by Sovietfowl** 2022-09-17 07:56 UTC
