### ISSUE TITLE
Every version after 1625 keeps crashing/stopping whenever try to enter any game!

### ISSUE THREAD

**Issue by 0sakib0** [skyline-emu/skyline#2161] opened 2023-01-22 19:04 UTC
Device: OnePlus 7
Soc: Snapdragon 855.
Android version:13 (Custom rom)

Version 1625 works perfectly but any version beyond this always crashes. Tried complete uninstall install, every possible driver but still crashes on newest versions. First I thought it might be a custom rom problem, but when I install version 1625 everything magically works again. attaching the verbose log file from latest version.
Thank You.(https://drive.google.com/file/d/10GoB9DZuGLxrJoTAXeHs6_VCwOEJY44E/view?usp=drivesdk)

**Comment by PeterNjeim** [comment] 2023-01-23 01:06
I can confirm this. I'm using a custom Android 13 ROM (Evolution X) and SD 855 as well. Xiaomi Mi 9T Pro is my phone. Maybe it's specific to the SD855. Thanks for sharing this because I was so confused why nothing was working

**Comment by ShinStyle** [comment] 2023-01-23 20:06
@PeterNjeim Hey, could you help me with a problem I have? What happens is that I have a perfect performance in that version but after a while the game freezes (I have tried it with cuphead)

**Comment by PeterNjeim** [comment] 2023-01-23 20:13
Maybe you're new to GitHub. You shouldn't be mixing multiple issues into one. Please make a new issue with your problem. Secondly, no reason to @ me specifically, anyone here might've been able to help you, not sure why you chose me. Thirdly, unfortunately I cannot help you and haven't played long enough to confirm or fail to reproduce your issue

**Comment by ShinStyle** [comment] 2023-01-23 20:17
ohh yes I'm new to github and sorry for the inconvenience

**Comment by PeterNjeim** [comment] 2023-01-24 00:32
@ShinStyle I didn't see you create a new issue so maybe you don't know how. Go to the Issues tab at the top and then on the right click the green New Issue button:
![image](https://user-images.githubusercontent.com/26418974/214185065-70534236-4f9b-4c71-b4fa-17c223780672.png)
Then you just make a title and describe your issue, then click the green Submit new issue button at the bottom

**Comment by Swizzlefowl** [comment] 2023-01-24 08:59
Hey, can you come to our discord server? It will be easier to troubleshoot your issues there.

**Comment by PeterNjeim** [comment] 2023-01-24 09:01
Sure, but can you minimize the off topic comments as well? If you have the power to do that

**Comment by 0sakib0** [comment] 2023-01-24 14:11
I am on Skyline official discord server where should I contact? I once sent message and screen record on the support section.

**Comment by 0sakib0** [comment] 2023-01-24 17:55
Is your device boot image magisk patched? or stock image?

**Comment by PeterNjeim** [comment] 2023-01-24 20:05
> Had this issue on a Mi 9t Pro as well, on a custom ROM. Somehow went away after I updated the ROM. Was on Evolution X(Early Nov. build) updated to latest build. 

I'm on the October 24th build but I'm currently not updating due to a regression in the keyboard in newer versions that the dev has confirmed is a feature. I won't get into the details but basically I'm not considering updating this ROM.

So maybe it's not an SD855 issue but rather something ROM devs of SD855 phones commonly did before December

**Comment by PeterNjeim** [comment] 2023-01-24 20:05
> Is your device boot image magisk patched? or stock image?

Does this question mean "are you using Magisk?"? If so, yes. If it means something else please let me know

**Comment by Swizzlefowl** [comment] 2023-01-24 20:09
This issue most likely seems to because of custom ROM, try using stock ROM instead. As this is really not an Skyline issue I will be closing it.

**Closed by Swizzlefowl** 2023-01-24 20:09 UTC

**Comment by PeterNjeim** [comment] 2023-01-24 20:33
Based on my reading of other related issues and discussion posts, I believe the problem is due to the "crashing issue" that earlier A13 ROM versions experienced (including my version). It's where certain combinations of apps refuse to open, videos crashing constantly in web browsers, etc. Newer versions of Skyline probably trigger this crash when opening the game. I think this perfectly explains it

**Comment by 0sakib0** [comment] 2023-01-28 05:35
> Had this issue on a Mi 9t Pro as well, on a custom ROM. Somehow went away after I updated the ROM. Was on Evolution X(Early Nov. build) updated to latest build.

Can you share your build number kindly?

**Comment by Osga21** [comment] 2023-02-01 12:14
Games load on this build: 
evolution_raphael-userdebug 13 TQ1A.230105.001.A2 1674156809 release-keys

**Comment by Aleksandar204** [comment] 2023-02-06 19:40
Can confirm this issue. Running YASP 13 (jan security patch) on a OnePlus 7 Pro and any version of Skyline newer than the one provided above crashes when opening any game.

**Comment by Mustafa1203v** [comment] 2023-05-01 21:08
> أستطيع أن أؤكد هذا. أنا أستخدم Android 13 ROM المخصص (Evolution X) و SD 855 أيضًا. Xiaomi Mi 9T Pro هو هاتفي. ربما هو خاص بـ SD855. نشكرك على مشاركة هذا لأنني كنت في حيرة من أمري بسبب عدم عمل أي شيء.
> 
> الإصدار الذي يعمل لمن يتساءلون: https://github.com/skyline-emu/skyline/suites/10074297652/artifacts/490659281 (ستنتهي صلاحيته بعد 90 يومًا ، لذا إذا كنت لا تزال بحاجة إليه بعد ذلك اسألني وسأرسله ) 




> أستطيع أن أؤكد هذا. أنا أستخدم Android 13 ROM المخصص (Evolution X) و SD 855 أيضًا. Xiaomi Mi 9T Pro هو هاتفي. ربما هو خاص بـ SD855. نشكرك على مشاركة هذا لأنني كنت في حيرة من أمري بسبب عدم عمل أي شيء.
> 
> الإصدار الذي يعمل لمن يتساءلون: https://github.com/skyline-emu/skyline/suites/10074297652/artifacts/490659281 (ستنتهي صلاحيته بعد 90 يومًا ، لذا إذا كنت لا تزال بحاجة إليه بعد ذلك اسألني وسأرسل هو - هي)

Can you send me a link to download the release?
