### ISSUE TITLE
Celeste crashes at the title screen

### ISSUE THREAD

**Issue by frans4080** [skyline-emu/skyline#440] opened 2022-03-09 09:01 UTC
celeste freezes after autosaving heres proof: 

https://user-images.githubusercontent.com/85518684/157409033-a91cb07c-9c17-4c7c-a630-d658387b00a5.mp4

**Comment by PixelyIon** [comment] 2022-03-09 14:38
Try to clear Skyline's data and cache but other than that if this occurs consistently then it's a device bug not a bug in the emulator, if by chance it does turn out to be an emulator bug then it'll probably be fixed by a VFS replacement.

**Comment by frans4080** [comment] 2022-03-09 16:58
clearing the cache and how do you replace the  vfs file, oh and also other games run fine it's only that's effected by it.

**Comment by PixelyIon** [comment] 2022-03-09 18:54
That's on our end, we're going to replace the entire VFS subsystem at some point. There's no "VFS file", all app data should be wiped by doing clear data. That'll probably make it work, if it still doesn't send over a log (with log level set to debug). It's likely an issue with your device though, we've seen weird permission bugs occur prior.

**Comment by PixelyIon** [comment] 2022-03-10 15:37
It's possible that you might need to buy a new phone (If you can't change get a custom ROM), but to be sure just post a log of the crash here.

**Comment by frans4080** [comment] 2022-03-11 08:13
how do i send logs from the emulator?

**Comment by NotAWeeb69** [comment] 2022-03-11 08:14
Its the button next to settings. Either save and attach it here or send it in #general in discord server

**Comment by frans4080** [comment] 2022-03-12 07:43
here you go https://mega.nz/file/1Z4EWKQZ

**Comment by Lamzas1234** [comment] 2022-03-12 07:58
need decryption key

**Comment by Bibiloux98** [comment] 2022-03-12 08:16
> need decryption key

You'll have to dump this file from your own Switch

**Comment by Lamzas1234** [comment] 2022-03-12 08:20
> > need decryption key
> 
> You'll have to dump this file from your own Switch

I meant the MEGA link

**Comment by Bibiloux98** [comment] 2022-03-12 08:23
> I meant the MEGA link

I assume you didn't get it. You need to buy a Nintendo Switch and dump files from it. You won't support any kind of support assuming that you're talking about piracy. That's illegal and the Skyline doesn't support piracy

**Comment by frans4080** [comment] 2022-03-12 10:53
sorry heres the code for the mege link: https://mega.nz/file/1Z4EWKQZ

**Comment by frans4080** [comment] 2022-03-12 10:54
sorry here's code for the mega link: u-yaBxnIwfG7UhaK3aRwV1xYHRWzIr6uIa6uLLpWsr0

**Comment by frans4080** [comment] 2022-03-12 14:43
did i send the wrong log?

**Comment by PixelyIon** [comment] 2022-03-12 14:57
No, it's a correct log and this is actually a known issue, it will be fixed at some point, I'll reopen the issue to track the status of the issue.
```
^^E^]22813^]GPFIFO^]Run: Signal: Segmentation fault @ 0x18F6015030 (PC: 0x710F0FD448)
Stack Trace:
* 0x710F0FD448 (memcmp from /apex/com.android.runtime/lib64/bionic/libc.so)
* 0x702042EE38 (skyline::gpu::interconnect::GraphicsContext::CompileShaderProgramState() from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x702042E0EC (void skyline::gpu::interconnect::GraphicsContext::Draw<false>(unsigned int, unsigned int, int) from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x702041FFD4 (skyline::gpu::interconnect::GraphicsContext::DrawVertex(unsigned int, unsigned int) from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x702041B56C (skyline::soc::gm20b::engine::maxwell3d::Maxwell3D::HandleMethod(unsigned int, unsigned int) from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x7020413D24 (skyline::soc::gm20b::engine::maxwell3d::Maxwell3D::CallMethodFromMacro(unsigned int, unsigned int) from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x702040F3B8 (skyline::soc::gm20b::engine::MacroInterpreter::Step(skyline::soc::gm20b::engine::MacroInterpreter::Opcode*) from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x702040E7A0 (skyline::soc::gm20b::engine::MacroInterpreter::Execute(unsigned long, skyline::span<unsigned int, 18446744073709551615ul>, skyline::soc::gm20b::engine::MacroEngineBase*) from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x7020411BC8 (skyline::soc::gm20b::engine::MacroEngineBase::HandleMacroCall(unsigned int, unsigned int, bool) from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x7020400FF4 (skyline::soc::gm20b::ChannelGpfifo::SendFull(unsigned int, unsigned int, skyline::soc::gm20b::SubchannelId, bool) from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x70204031EC (from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x70204026AC (from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x7020401CAC (from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x702040169C (skyline::soc::gm20b::ChannelGpfifo::Process(skyline::soc::gm20b::GpEntry) from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x70204053F8 (from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x7020401F44 (from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x7020400980 (skyline::soc::gm20b::ChannelGpfifo::Run() from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x7020404380 (from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x7020404310 (from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x7020403FF8 (from /data/app/skyline.emu-iLw8DGWqwmAnpXm6_M1NQQ==/lib/arm64/libskyline.so)
* 0x710F164B74 (from /apex/com.android.runtime/lib64/bionic/libc.so)
* 0x710F102EB0 (from /apex/com.android.runtime/lib64/bionic/libc.so)
```

**Comment by frans4080** [comment] 2022-03-12 20:47
thats good to know, i hope this issue will be fixed.

**Comment by NEWLuigi64** [comment] 2022-03-13 17:13
Weird, Celeste doesn't crash for me

**Comment by frans4080** [comment] 2022-03-15 21:32
probably because you're device isn't a oneplus device.

**Comment by frans4080** [comment] 2022-03-27 12:22
you probably forgot about this issue already.

**Comment by PixelyIon** [comment] 2022-03-27 15:38
No, I haven't. It's actually related to #416 so I think I'll supersede it with that issue. If it does occur after I fix that issue feel free to reopen this.

**Closed by PixelyIon** 2022-03-27 15:38 UTC

**Comment by frans4080** [comment] 2022-03-30 07:16
it still crashes.

**Comment by frans4080** [comment] 2022-03-30 07:16
and i can't reopen the issue.

**Comment by frans4080** [comment] 2022-03-30 18:10
also what was the point of closing this issue if it isn't fixed?

**Comment by PixelyIon** [comment] 2022-03-30 18:14
We get notifications for every message and would recommend sending a single message rather than multiple spread minutes apart, as mentioned above this issue has been superseded by #416. It will likely be fixed when #416 is, if it doesn't you can leave a message here and this will be reopened.

**Comment by frans4080** [comment] 2022-03-30 18:16
oh.

**Comment by sauradipdebnath** [comment] 2022-04-05 10:30
Reopen this issue

**Comment by frans4080** [comment] 2022-04-08 18:35
issue #416 is still open.

**Comment by frans4080** [comment] 2022-04-08 18:53
actually that won't nessecary cause the the game now works.

**Comment by Woganog** [comment] 2022-04-08 19:35
They fixed it in the nce memory update
