### ISSUE TITLE
Screen flickering on Mali GPUs

### ISSUE THREAD

**Issue by sauradipdebnath** [skyline-emu/skyline#300] opened 2022-01-06 09:32 UTC
It's a previous and the present image blinking 
 Can you fix it to smooth motion

**Comment by Allatel** [comment] 2022-01-06 10:48
Another one :)

**Comment by Infinity-Loops** [comment] 2022-01-06 11:33
This is a Vulkan Driver problem with non Adreno GPU's

**Comment by SxDVibes19238e** [comment] 2022-01-06 13:38
Hello @Infinity-Loops so is there any fix for non adrenal GPUs

**Comment by chiko28** [comment] 2022-01-06 13:51
Blinking images and graphic delays on android 10, infinix hot 10, specifically.
![Screenshot_20220106-214613](https://user-images.githubusercontent.com/20987937/148392976-f6438c75-df76-4860-b4f5-2ee4f2da3c08.png)

**Comment by SxDVibes19238e** [comment] 2022-01-06 13:54
Oh mine is Android 10 (I guess)

**Comment by PixelyIon** [comment] 2022-01-06 14:03
This is a known issue on Mali GPUs, it'll be debugged by @lynxnb who can reproduce it on an Exynos S9. Usage of Skyline is not recommended for people with photosensitive epilepsy due to the potential for visual glitches.

**Comment by SxDVibes19238e** [comment] 2022-01-06 15:15
Oh soo there will be a fix soon?

**Comment by sauradipdebnath** [comment] 2022-01-07 06:34
> This is a known issue on Mali GPUs, it'll be debugged by @lynxnb who can reproduce it on an Exynos S9

**Comment by sauradipdebnath** [comment] 2022-01-07 06:43
> Oh soo there will be a fix soon?

Yess there must be a fix

**Comment by sauradipdebnath** [comment] 2022-01-08 09:27
On new update no graphic output is there

**Comment by chiko28** [comment] 2022-01-08 10:01
https://user-images.githubusercontent.com/20987937/148640080-e9c1f0b8-af4d-47b2-a414-d04b7026e7e4.mp4

Flickering gone but, stays on being blackscreen even though theres sounds and can click buttons of game.

**Comment by PixelyIon** [comment] 2022-01-08 10:02
That is on `fmt-consteval` not the `ftx1` branch, only report issues regarding graphics on the `ftx1` branch. The other one doesn't have the GPU implementation and is an entirely different branch.

**Comment by ChrisM20** [comment] 2022-01-09 23:32
Fixed in kirin 980

**Comment by Bibiloux98** [comment] 2022-01-09 23:36
Last update fixed the Mali issues ! Thanks guys

**Comment by chiko28** [comment] 2022-01-10 00:16
Congrats for flickering and blacksreen fix, although the fps stays at 14-18fps even when skyline setting is using max 60fps option. Therefore the game is very slow.

**Comment by Bibiloux98** [comment] 2022-01-10 00:18
> Congrats for flickering and blacksreen fix, although the fps stays at 14-18fps even when skyline setting is using max 60fps option. Therefore the game is very slow.

It depends on your phone, what phone do you have ? With a Pixel 6, I have constant 45fps

**Comment by chiko28** [comment] 2022-01-10 00:22
I have android 10, infinix hot 10.

**Comment by lynxnb** [comment] 2022-01-12 12:54
Same issue as #313 and #301, which have been fixed.

**Closed by lynxnb** 2022-01-12 12:54 UTC

**Comment by Tiredasfunk** [comment] 2022-08-07 06:17
7 months huh time flies by

**Comment by moises0000** [comment] 2022-09-25 04:56
Drivers MALI ,PLEASE

**Comment by Dekuzearou** [comment] 2022-09-25 04:58
> Drivers MALI ,PLEASE

This will never happen

**Comment by AdriFarofenix23** [comment] 2022-09-25 07:14
Then fix Mali egg ns is best with Mali GPU fix Mali in skyline
