### ISSUE TITLE
mali gpus compatibility(Exynos))

### ISSUE THREAD

**Issue by deividariel0909** [skyline-emu/skyline#1401] opened 2022-05-28 21:54 UTC
Unfortunately gpu mali users are being bounced back note (used to work) please bring a compatibility for gpus mali i know its hard but please thank you very much worth remembering #mine is Exynos

**Comment by deividariel0909** [comment] 2022-05-28 21:55
Up

**Comment by Sovietfowl** [comment] 2022-05-29 09:03
Duplicate of issue #987

**Closed by Sovietfowl** 2022-05-29 09:03 UTC
