### ISSUE TITLE
sir fix this problem please dimensity 1200 processor playable please sir

### ISSUE THREAD

**Issue by Gamexzeus** [skyline-emu/skyline#1599] opened 2022-06-21 16:44 UTC
sir fix this problem please dimensity 1200 processor playable please sir

**Comment by Sovietfowl** [comment] 2022-06-21 16:49
Duplicate of issue #987

**Closed by Sovietfowl** 2022-06-21 16:49 UTC

**Comment by Sovietfowl** [comment] 2022-06-21 16:52
Resident evil 5 doesn't work yet.

**Comment by mr-hopeless** [comment] 2022-06-21 17:02
> Duplicate of # which game will play REALME X7 max sir please help me

Take a look at https://github.com/skyline-emu/skyline-games-list.

**Comment by Gamexzeus** [comment] 2022-06-21 17:12
Sir but which game playable my device realme X7 max please send me name

**Comment by Gamexzeus** [comment] 2022-06-21 17:18
Duplicate of # Sir but which game playable my device realme X7 max please send me name

**Comment by Sovietfowl** [comment] 2022-06-21 17:20
Please stop spamming the repository, there is a compatibility list for games which currently work. https://github.com/skyline-emu/skyline-games-list.
