### ISSUE TITLE
Updates/DLC's.

### ISSUE THREAD

**Issue by kolp0** [skyline-emu/skyline#1414] opened 2022-05-29 07:20 UTC
### Discussed in https://github.com/skyline-emu/skyline/discussions/1361

<div type='discussions-op-text'>

<sup>Originally posted by **Jeff-2612** May 22, 2022</sup>
The Skyline team can implement in Skyline a method to install update/DLC's.</div>

**Comment by Sovietfowl** [comment] 2022-05-29 09:06
Duplicate of issue #1392.

**Closed by Sovietfowl** 2022-05-29 09:06 UTC
