### ISSUE TITLE
Cannot type letters in game with phone keyboard?

### ISSUE THREAD

**Issue by Machannn** [skyline-emu/skyline#1228] opened 2022-05-09 07:16 UTC
I wonder if there's a way to make typing in game works? I tried to type in my name on my game but it just crashed and it didn't even let the keyboard to show up, can we still type with PC keyboard? Thank you in advance<3

**Comment by PixelyIon** [comment] 2022-05-10 20:49
Duplicate of #328, will be closing this issue as a result.

**Closed by PixelyIon** 2022-05-10 20:49 UTC
