### ISSUE TITLE
Skyline emulator not installing on s21 android 12

### ISSUE THREAD

**Issue by robloxoofman** [skyline-emu/skyline#939] opened 2022-04-09 01:31 UTC
Tried to download skyline, removed my current skyline application accidentally pressed keep data and uninstall and now it's just "Would you like to update this app" when it's uninstalled!

**Comment by Jariel87** [comment] 2022-04-09 05:31
Remove the data folder from root storage

**Comment by PixelyIon** [comment] 2022-04-11 05:01
Duplicate of #352.

**Closed by PixelyIon** 2022-04-11 05:01 UTC
