### ISSUE TITLE
Games not working

### ISSUE THREAD

**Issue by karmakarsouvik** [skyline-emu/skyline#1251] opened 2022-05-11 07:31 UTC
Every games is crashing in #1090 build

**Comment by Thepowa753** [comment] 2022-05-11 07:38
I attached a log about odyssey on it's [game issue](https://github.com/skyline-emu/skyline-games-list/issues/1)
I continue to update the issue for any significant changes

**Comment by PixelyIon** [comment] 2022-05-11 07:41
Duplicate of #1246.

**Closed by PixelyIon** 2022-05-11 07:41 UTC
