### ISSUE TITLE
save game can't be copied?

### ISSUE THREAD

**Issue by ikhoeyZX** [skyline-emu/skyline#2228] opened 2023-03-02 12:21 UTC
It's weird, all file manager even using build in file manager, i can't copy but can delete / rename 'crystar' saves file
I can replace it but can't backup it, any solution?
Saves file didn't corrupt
![Screenshot_20230302_201448_ZArchiver](https://user-images.githubusercontent.com/79812109/222426664-f503cfd7-bd55-4bba-bacf-0cc553f3055b.png)
![Screenshot_20230302_201946](https://user-images.githubusercontent.com/79812109/222427084-85d2b147-707d-4dfe-bb87-5dd371ba6951.png)

**Comment by Swizzlefowl** [comment] 2023-03-02 13:32
Duplicate of issue #1814

**Closed** 2023-03-02 13:32 UTC
