### ISSUE TITLE
add MOD features to each game

### ISSUE THREAD

**Issue by Ahmadrizal894** [skyline-emu/skyline#1643] opened 2022-06-30 14:51 UTC
like the yuzu emulator which provides a MOD feature so that we can add mod files to each game

**Comment by yhak22** [comment] 2022-06-30 20:18
Plz 
Don't double your issues

**Comment by Ahmadrizal894** [comment] 2022-06-30 23:12
sorry, looks like my github has a problem

**Comment by Crytonics** [comment] 2022-07-03 11:14
Duplicate of https://github.com/skyline-emu/skyline/issues/1639

**Closed** 2022-07-03 11:25 UTC
