### ISSUE TITLE
Most recent version not working with Mali gpu (S10e)

### ISSUE THREAD

**Issue by Suenco** [skyline-emu/skyline#1904] opened 2022-10-11 17:02 UTC
Not launching any games on s10e with Mali gpu and exynos processor. Anyone having the same issue? Keep getting Black screen after laucing pokémon leta Go Pikachu de for example!

**Comment by Sovietfowl** [comment] 2022-10-11 17:06
Duplicate of issue #1820.

**Closed by Sovietfowl** 2022-10-11 17:06 UTC
